### ISSUE TITLE
Still getting "cannot import name 'NaN' from numpy" error 

### ISSUE THREAD

**Issue by dmike23** [twopirllc/pandas-ta#857]
**Which version are you running? The lastest version is on Github. Pip is for major releases.**
```python
import pandas_ta as ta
print(ta.version)
```
Version: 0.3.14b0

**Do you have _TA Lib_ also installed in your environment?**
```sh
$ pip list
```
no. should i?

**Have you tried the _development_ version? Did it resolve the issue?**
```sh
$ pip install -U git+https://github.com/twopirllc/pandas-ta.git@development
```
yes and it did not solve it.

**Describe the bug**

Still getting "cannot import name 'NaN' from numpy" error and have tried suggested solutions with no luck. 

**To Reproduce**
Provide sample code.
```python
import pandas as pd
import pandas_ta as ta

file_path = r'C:\Users\micha\OneDrive\Desktop\Algo Switcher Model\combined_output.txt'  # Replace with the actual path to your combined_output.txt

data = pd.read_csv(file_path, delimiter=';', header=None)

data['ATR'] = ta.atr(data['High'], data['Low'], data['Close'], length=14)
data['ADX'] = ta.adx(data['High'], data['Low'], data['Close'], length=14)['ADX_14']
data['+DI'] = ta.adx(data['High'], data['Low'], data['Close'], length=14)['DMP_14']
data['-DI'] = ta.adx(data['High'], data['Low'], data['Close'], length=14)['DMN_14']`
```

**Expected behavior**

import pandas_ta should work !

**Screenshots**

![image](https://github.com/user-attachments/assets/e0fe2fac-5504-4cf1-8c30-5839bb1926f9)

![image](https://github.com/user-attachments/assets/c9f273dd-5e88-476c-9ea9-ddbeb821bf80)

**Additional context**

Changed the squeeze pro file to "from numpy import nan" from "from numpy import NaN as npNaN"

also tried having it as "from numpy import nan as npNaN"

neither solution worked. 

Running in visual studio 2022. Python 3.9 64-bit.

**Comment by twopirllc** [comment]
Hello @dmike23 & @ivorynoise,

> 0.3.14b0

However based on the squeeze_pro.py screenshot, you are running some _development_ version yet unidentified.

> TA-Lib? no. should i?

User choice.

> Still getting "cannot import name 'NaN' from numpy" error and have tried suggested solutions with no luck.

What other solutions have you tried? Be specific with the Issue numbers please.

> import pandas_ta should work !

Yes, absolutely. However I have been asking for help and support for years …. 🤷🏼‍♂️ 

Furthermore, you have also neglected to share which dependency versions you are using for the _development_ branch. See the _development_ requirements.txt below to ensure you have the minimum requirements.

If it is a numpy 2.x issue:

> I have addressed and **explained** this already. 😑  Most notably in the following Issues and PRs: #799, #801, #811, #836. Please read (again) and follow any and **all**  relevant links for extra details.  Furthermore, please familiarize yourself the [Guidelines](https://github.com/twopirllc/pandas-ta/blob/development/CODE_OF_CONDUCT.md).
> 
> In short, based on the my replies in those posts:
> 
> - It's **not** dead nor is it a high churn library. Please use the _development_ version. 😎 
> - Pandas TA depends on TA Lib which **also** has Numpy 2 issues.  🤷🏼‍♂️ 
>    - Please advise on expediting the Numpy 2 fix for TA Lib so there is no more log jam and everyone benefits.
> - Python 3.12 [removed setuptools](https://docs.python.org/3.12/whatsnew/3.12.html), hence it is required for installation. Furthermore, it is listed in the _development_ [requirements.txt](https://github.com/twopirllc/pandas-ta/blob/development/requirements.txt). 

Lastly, make sure you have read up on **all** the links posted above so you are aware of what has happened and I can avoid repeating myself. 😉 

Kind Regards,
KJ

**Comment by rifatHaqueGIT** [comment]
I was trying to figure out how to get Pandas ta to work around the numpy situation. I downgraded my numpy version but now im getting this error
![image](https://github.com/user-attachments/assets/39568ca3-54a6-4f23-8ac6-b154af62a9b7)
I tried changing all my library versions to the ones listed in requirements.txt(these are my versions):
![image](https://github.com/user-attachments/assets/cd86b29b-04ad-4148-b8ba-37041f5b7d57)
My python version is 3.10.5, I downgraded from 3.12 since this library has conflicts with that version. Any ideas what I'm doing wrong to get this error?

**Comment by joaoe** [comment]
> Yes, absolutely. However I have been asking for help and support for years …. 🤷🏼‍♂️

You have it fixed in the development branch, which has 351 commits more than main. Will you ever make new tags and publish a new version ?

**Comment by twopirllc** [comment]
@joaoe 

> You have it fixed in the development branch, which has 351 commits more than main. Will you ever make new tags and publish a new version ?

> Yes, absolutely. However I have been asking for help and support for years …. 🤷🏼‍♂️

But again ...
> - It's not dead nor is it a high churn library. Please use the development version. 😎

Lastly, please spend a little time reading the links I shared above **and** the _development_ [README](https://github.com/twopirllc/pandas-ta/blob/development/README.md).

**Comment by twopirllc** [comment]
Hello @rifatHaqueGIT,

Created a new issue #859, for this unrelated result. All communication for that problem should continue there.

Kind Regards,
KJ

**Comment by angelaponte** [comment]
I'm seeing this as well and have pandas_ta working fine in python 3.12.3, on Windows 10, installed via Anaconda.

My issue is when I create a Linux container image (what I've been battling most of the day), using Ubuntu 22 LTS or public.ecr.aws/docker/library/python:3.12.3-slim as a base image, and install all my required packages.

It feels like a garden variety python dependency hell issue to me. If I find a solution, I'll post my Dockerfile.

**Comment by angelaponte** [comment]
I can confirm that the package loads in python 3.12.3 in a Linux container.

My base image is:
public.ecr.aws/docker/library/python:3.12.3-slim

Key package versions are:
numpy>=1.26.0 \
pandas>=2.2.0

I installed the pandas_ta version from Github:
git+https://github.com/twopirllc/pandas-ta

Here's a show and tell:
$ cat pandas_ta_demo.py
import pandas_ta

print(pandas_ta.__version__)

$ python pandas_ta_demo.py
0.3.14b0

I think this is the modern day version of . . . it works on my computer . . . err . . . container?

**Comment by SnowDeMen** [comment]
Go ahead and go to the pandas-ta folder in your packages.

![Image](https://github.com/user-attachments/assets/1b0f55c7-403e-42ff-bf15-c710aa330fa5)

Then click on:
> momentum > squeeze_pro.py

Edit

Go ahead and remove this line:
`from numpy import NaN as npNaN`

And sustitute with the following lines:
```
import numpy as np
npNaN = np.nan
```

Save it and it should be working.

> On a side note, I know that this is not the optimal solution. But this should be fixed ASAP, as this problem has persisted through the past months.

**Comment by chachako** [comment]
I'm also experiencing this issue with Python 3.13 and the latest pandas-ta. I tried modifying the squeeze_pro.py file but still encountering issues. Looking forward to an official fix.

**Comment by twopirllc** [comment]
Please see #901
